#!/bin/sh

# Generate cscope DB and ctags under source dir.

Platform=`uname`
CSCOPE_FILE=cscope.files
TAG_FILE=tags
SRCDIR=$PWD
BASEDIR=$PWD
ctags_opt="--file-scope=no"
ctags_cmd=ctags
if [[ "$Platform" == 'Linux' ]]
then
	ctags_cmd=/usr/bin/ctags
fi

cd $BASEDIR
> $CSCOPE_FILE
for dir in base bcm bcm-switch bcm2 flash click elts-meraki hostap meraki openwrt qca-nss wlan wpa_supplicant
#for dir in base click elts-meraki hostap meraki qca-nss wlan
do
	if [[ "$Platform" == 'Linux' ]]
	then
		find $SRCDIR/$dir -regex ".*\.\(h\|c\|hh\|hpp\|cc\|cpp\|cxx\|s\|S\|x\)" -not -path "$SRCDIR/base/build_*" -print >> $BASEDIR/$CSCOPE_FILE
	else
		find $SRCDIR/$dir  \(			\
			-name "*.h" -or 	\
			-name "*.c" -or 	\
			-name "*.hh" -or 	\
			-name "*.cc" -or 	\
			-name "*.cpp" -or	\
			-name "*.hpp" -or	\
			-name "*.cxx" -or	\
			-name "*.s" -or		\
			-name "*.x" -or		\
			-name "*.x" \) -not -path "$SRCDIR/base/build_*" -print >> $BASEDIR/$CSCOPE_FILE
	fi
done

cscope -b -q -k

# ctags recursively search for tags under current dir, so hide tags under .git
rm -f $BASEDIR/.git/$TAG_FILE
$ctags_cmd $ctags_opt -R -f $BASEDIR/.git/$TAG_FILE $SRCDIR/base $SRCDIR/click $SRCDIR/meraki $SRCDIR/elts-meraki  $SRCDIR/hostap $SRCDIR/qca-nss $SRCDIR/wlan
