#!/bin/sh

# Generate cscope DB and ctags.

Platform=`uname`
CSCOPE_FILE=cscope.files
TAG_FILE=tags
SRCDIR=$PWD
BASEDIR=$PWD
ctags_opt="--file-scope=no"
ctags_cmd=ctags
if [[ "$Platform" == 'Darwin' ]]
then
	ctags_cmd=/usr/local/bin/ctags
fi

cd $BASEDIR
> $CSCOPE_FILE
for dir in $PWD `ls -d $PWD/*`
do
	if [[ "$Platform" != 'Darwin' ]]
	then
		find $dir -regex ".*\.\(h\|c\|hh\|hpp\|cc\|cpp\|cxx\|s\|S\|x\|click\|sh\|py\|go\)" -print >> $BASEDIR/$CSCOPE_FILE
	else
		find $dir  \(			\
			-name "*.h" -or 	\
			-name "*.c" -or 	\
			-name "*.hh" -or 	\
			-name "*.cc" -or 	\
			-name "*.cpp" -or	\
			-name "*.hpp" -or	\
			-name "*.cxx" -or	\
			-name "*.s" -or		\
            -name "*.S" -or		\
			-name "*.x" -or		\
            -name "*.sh" -or		\
            -name "*.py" -or		\
			-name "*.click" \) -print >> $BASEDIR/$CSCOPE_FILE
	fi
done

cscope -b -q -k

rm -f $BASEDIR/.git/$TAG_FILE 2>/dev/null
$ctags_cmd $ctags_opt -R -f $BASEDIR/.git/$TAG_FILE $SRCDIR
#$ctags_cmd $ctags_opt -R -f $BASEDIR/.git/$TAG_FILE $SRCDIR/base/click-config $SRCDIR/click $SRCDIR/meraki $SRCDIR/elts-meraki  $SRCDIR/hostap $SRCDIR/qca-nss $SRCDIR/wlan
