#!/bin/sh

# Generate cscope DB and ctags.

Platform=`uname`
CSCOPE_FILE=cscope.files
TAG_FILE=tags
SRCDIR=
BASEDIR=
ctags_opt="--file-scope=no"
ctags_cmd=ctags
if [[ "$Platform" == 'Linux' ]]
then
	SRCDIR=/nobackup/bobyan/router
	BASEDIR=/nobackup/bobyan/cscope/$Platform
	ctags_cmd=/usr/bin/ctags
else
	SRCDIR=$HOME/Documents/VMs/router
	BASEDIR=$HOME/Documents/VMs/cscope/$Platform
fi

cd $BASEDIR
> $CSCOPE_FILE
for dir in base bcm bcm-switch bcm2 flash click elts-meraki hostap meraki openwrt qca-nss wlan wpa_supplicant
#for dir in base click elts-meraki hostap meraki qca-nss wlan
do
	if [[ "$Platform" == 'Linux' ]]
	then
		find $SRCDIR/$dir -regex ".*\.\(h\|c\|hh\|hpp\|cc\|cpp\|cxx\|s\|S\|x\)" -not -path "$SRCDIR/base/build_*" -print >> $BASEDIR/$CSCOPE_FILE
	else
		find $SRCDIR/$dir  \(			\
			-name "*.h" -or 	\
			-name "*.c" -or 	\
			-name "*.hh" -or 	\
			-name "*.cc" -or 	\
			-name "*.cpp" -or	\
			-name "*.hpp" -or	\
			-name "*.cxx" -or	\
			-name "*.s" -or		\
			-name "*.x" -or		\
			-name "*.x" \) -not -path "$SRCDIR/base/build_*" -print >> $BASEDIR/$CSCOPE_FILE
	fi
done

cscope -b -q -k

rm -f $BASEDIR/$TAG_FILE
$ctags_cmd $ctags_opt -R $SRCDIR/base $SRCDIR/click $SRCDIR/meraki $SRCDIR/elts-meraki  $SRCDIR/hostap $SRCDIR/qca-nss $SRCDIR/wlan --extra=+f -f $BASEDIR/$TAG_FILE
